package:
  name: ifcopenshell
  version: 0.8.0

source:
  path: ../../IfcOpenShell

build:
  script: |
    BUILD_CFG=Release python nix/build-all.py --without-hdf5 --without-opencollada --without-swig --without-pcre -v --wasm --py312 IfcOpenShell-Python
    mv package/ifcopenshell .
    cp pyodide/setup.py .
    mv dist/IfcOpenShell-0.8.0-py3-none-any.whl dist/ifcopenshell-python-v0.8.0-${GITHUB_SHA:0:7}-cp312-cp312-emscripten_3_1_58_wasm32.whl

about:
  home: http://ifcopenshell.org
  license: LGPL-3.0-or-later
  summary: |
    IfcOpenShell is an open source (LGPL) software library for 
    working with the Industry Foundation Classes (IFC) file format.
